### PR TITLE
Default attributes

### PR DESCRIPTION
**Pull request by hallgren**
Issue #43

Its possible to add a default_attributes function in an AggregateRoot and set default values to already created aggregates.

Ex: After a aggregate is created its possible to add default values that will be set when the aggregate is rebuilt.

### CODE REVIEW

**Comment by jesjos** [comment]
Maybe `Sandthorn::AggregateRoot` should define a default `default_attributes` method so that we don't have to check to see if we respond to it?

```ruby
def default_attributes
  # NOOP
end
```

**Comment by hallgren** [comment]
Is it a nice pattern to have an empty method laying around like that?

**Comment by jesjos** [comment]
I think it's more confident than nervously checking `respond_to?`

**Comment by hallgren** [comment]
You win.

**Pull request merged**
