### PR TITLE
New Event Driver API

### PR DESCRIPTION
**Pull request by jesjos**
The Event Driver API will change a bit in the next release. 

NB THIS IS A STAGING AREA, DON'T MERGE

### CODE REVIEW

**Comment by jesjos** [comment]
So `sandthorn_sequel_driver` currently only supports `ruby >=2.1`. Should we rewrite to support ruby 2.0 or should we drop it? I think the errors mainly come from required keyword args, a feature that was introduced in ruby 2.1. Whaddaya think, @larskrantz and @hallgren

**Comment by hallgren** [comment]
2.0 is a pretty used version according to https://semaphoreci.com/blog/2014/08/27/ruby-version-usage-in-commercial-projects-2014-edition.html. Haven´t looked more in depth on the usage of 2.0 and >= 2.1,  but if its an easy change why not support 2.0.

**Comment by larskrantz** [comment]
I'm all for supporting higher version, 2.1, like the keyword args too much.

**Comment by jesjos** [comment]
In ruby 2.1 we can do this:

    def foo(bar:, baz:)
    end

`bar` and `baz` are required.

In ruby 2.0 we still have keyword args, but they have to have defaults:

    def foo(bar: nil, baz: nil)
    end

You can make your own hack by doing something like this:

    def foo(bar: no_bar, baz: no_baz)
    end

    def no_bar
      raise "Keyword missing: bar"
    end

    def no_baz
      raise "Keyword missing: baz"
    end

I'm kinda thinking we probably should support 2.0, but also like the idea of going all-out modern-ruby-only. Argh. Decisions.

**Comment by jesjos** [comment]
Okay, I went with supporting ruby 2.0

**Comment by hallgren** [comment]
Looks nice, is it ok with you @larskrantz ?

**Comment by larskrantz** [comment]
It's ok!

**Comment by jesjos** [comment]
This PR contains breaking changes to how it works with the event store driver. So that kinda tells us it should be a major version bump. On the other hand, I'd say Sandthorn is still under development, and "prerelease" libs (major version 0) often release breaking changes and only bump a minor, since the API is considered to be unstable anyway. So maybe we'll just call this Sandthorn 0.7.0?

**Comment by jesjos** [comment]
A problem is that Sandthorn has a confused relationship with `sandthorn_driver_sequel`. It really shouldn't depend on a specific driver since we you to be able to swap drivers. But it does depend on the driver API, which has changed between version 1 and 2. Perhaps there should be an event store gem that just presents a stable public API. Event Store drivers could also depend upon that gem and voilà - we have decent version control using gems again.

**Comment by jesjos** [comment]
I'm going to call this version 0.7.0. I think we're still in development territory.

**Pull request merged**
